### ISSUE TITLE
Gerber for the VDP relief board

### ISSUE THREAD

**Issue by OlivierGrimard** [zaxour/TripleBypassV2Plus#2]
Hi @zaxour , could you please add the gerber file for the VDP relief board? I would like to try it because this part is not easy to solder and I think it will help a lot for the installation.

Thank you.
Olivier

**Comment by zaxour** [comment]
Hi,

It’s available here:

https://github.com/zaxour/M1ReliefBoard

Hope this helps!

**Comment by OlivierGrimard** [comment]
Thank you :)
