### ISSUE TITLE
Sega Genesis TripleBypass M2VA3 Missing Pic

### ISSUE THREAD

**Issue by tmcbity** [zaxour/TripleBypassV2Plus#3]
Hello,

Hope this message finds you well.

It appears that your Genesis TripleBypass M2VA3 instructions are missing a picture under the "M2VA3- 3BP Jumpers" heading. Am I possibly missing something?

Thank you so much for putting these instructions together!

Also, thank you for your time!

**Comment by zaxour** [comment]
Hi,

The lack of a picture was intentional. You only need to solder the "2"
jumpers (both of them) for the Model 2 VA3 installation.

Although, thinking about it, having a labeled diagram of the board with
those highlighted might make it more clear.

Thanks,
Zack

**Comment by tmcbity** [comment]
Thank you so much good sir, you are awesome.

My apologies for the stupid question. I am a beginner hobbyist and I really want to learn. I have a background in engineering, just not electronics.

Last question:

I noticed that I received 3 resistors with the sega triple bypass (retrorbg - I tried ordering from you, but you were out of stock). Are these just for the model 1? Are they necessary for the model 2? I understand that the bypass does not properly replicate the Sega RGB circuit in the model 1, which includes 3 resistors. Is this also an issue for the model 2?

Thank you so much!

Igor Koracin

**Comment by zaxour** [comment]
Igor,

Yes, those should be 5.6K resistors and are only necessary on model 1 installs, since the VDP RGB pins are typically lifted and thus the open collector outputs of the VDP are no longer properly loaded. A model 2 install does not require them unless it is desired to lift the RGB pins for some reason.

Zack

**Comment by tmcbity** [comment]
Thank you so much for the prompt response and information, my friend. Anything cool I can purchase from your store that you suggest? I'm a collector and have most consoles.
