### ISSUE TITLE
Sega CDX sound issues

### ISSUE THREAD

**Issue by TruREALigion** [zaxour/TripleBypassV2Plus#6]
2 questions:

1.
I seem to have ruined the pad for PSG.  Is there an alternative spot I can wire up to?

2.
On the section where I wire up SR and SL I did not change/replace R75 and R76 to 4.7K  That are originally 11K (code113).  Is this critical to change?

My current issues are:
-Cartridge games no sound
-Sega CD BIOS screen has weird sounds (maybe related to PSG not wired as per the install guide?)
-Sega CD BIOS “Sonic screen” where the game loads has no sound (where the sparkle chime from left to right plays).

CD sound is perfect however.

**Comment by zaxour** [comment]
I would need to see photos of your install to troubleshoot.

Zack

**Comment by TruREALigion** [comment]
> I would need to see photos of your install to troubleshoot. Zack
> […](#)
> On Oct 12, 2024 at 21:45 -0600, TruREALigion ***@***.***>, wrote: I followed the guide, but did not change/replace R75 and R76 to 4.7K. That are originally 11K (code113). would this be the reason I am not getting sound? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

I realized this isn’t even your board so I will reach out to Tienfeng.  I have yet to figure out where to connect PSG because I broke the pad…

![IMG_9332](https://github.com/user-attachments/assets/939c2b32-38cc-4514-b3f7-b85460fad50d)

**Comment by zaxour** [comment]
The connections should be the same. Make sure you’re testing with the CD board attached.

**Comment by TruREALigion** [comment]
> The connections should be the same. Make sure you’re testing with the CD board attached.
> […](#)
> On Oct 13, 2024 at 11:43 -0600, TruREALigion ***@***.***>, wrote: > I would need to see photos of your install to troubleshoot. Zack > … > On Oct 12, 2024 at 21:45 -0600, TruREALigion @.>, wrote: I followed the guide, but did not change/replace R75 and R76 to 4.7K. That are originally 11K (code113). would this be the reason I am not getting sound? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.> I realized this isn’t even your board so I will reach out to Tienfeng. I have yet to figure out where to connect PSG because I broke the pad… IMG_9332.jpeg (view on web) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

Yeah the console turns on fine, sound (32X. CD) in general works, just that I did not replace R75 and R76, and the PSG i connected to a different spot on the back of the board (which is probably incorrect).
Do you happen to know if R75/R76 is a requirement to replace?

**Comment by zaxour** [comment]
It would just increase the gain on the cartridge audio stuff, but if you're
getting 32X sound, that would mean that there's an issue with your FM
audio, since the 32X audio also goes through the same paths.

**Comment by TruREALigion** [comment]
I have resolved all sound issues by successfully probing another point for the PSG signal on the rear.  Hopefully nobody has to do this because of my mistake of breaking the pad!
![PSG-rear-correction](https://github.com/user-attachments/assets/2707748c-467e-4a07-86f7-1dd994f17208)
